logging.level.org.springframework.web.client.RestTemplate=DEBUG
server.port=8080
shareit-server.url=http://localhost:9090

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
